name: Bot Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: docker build -t my-bot-image .
      - name: Deploy
        run: |
          docker stop bot-container || true
          docker rm bot-container || true
          docker run -d --name bot-container my-bot-image
